networks:
  internal:
  frontend:
    external: true

services:
  sync-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crdt-sync-server
    env_file:
      - ../../.env-sync-server
    ports:
      - "3002:3002"
    networks:
      - internal
