stages:
  - build
  - update_portainer-qa

master_build:
  stage: build
  variables:
    REGISTRY_ADDRESS: 'registry.dnamicro.com'
    REGISTRY_USERNAME: 'dna'
    REGISTRY_PASSWORD: 'aBGioazrbkrFvG5XSdgB'
    PROJECT_IMAGE_PREFIX: 'platform'
  script:
    - echo 'Image build successfully'    
  only:
    - 'development'

update_stack:
  stage: update_portainer-qa
  variables:
    ENDPOINT_ID: 2
    STACK_ID: 83
    PORTAINER_USERNAME: 'ci'
    PORTAINER_PASSWORD: 'fZmcpMHDpp63yKiszHL3'
    PORTAINER_HOST: https://portainer.dnaqa.net
    PORTAINER_YML_FILE: platform-template.yml
    FILE_PATH: /var/apps/portainer
    REGISTRY_ADDRESS: 'registry.dnamicro.com'
    REGISTRY_USERNAME: 'dna'
    REGISTRY_PASSWORD: 'aBGioazrbkrFvG5XSdgB'
    PROJECT_IMAGE_PREFIX: 'platform'
  script:
    - 'docker login $REGISTRY_ADDRESS -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD'
    - "docker build -t $REGISTRY_ADDRESS/$PROJECT_IMAGE_PREFIX-$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID -f dockerfile \
      --build-arg PROJECT=$CI_PROJECT_NAME ."
    - 'docker tag $REGISTRY_ADDRESS/$PROJECT_IMAGE_PREFIX-$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID $REGISTRY_ADDRESS/$PROJECT_IMAGE_PREFIX-$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME'
    - 'docker push $REGISTRY_ADDRESS/$PROJECT_IMAGE_PREFIX-$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME-$CI_PIPELINE_ID'
    - 'docker push $REGISTRY_ADDRESS/$PROJECT_IMAGE_PREFIX-$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME'

    #------------------------------ Update Portainer ---------------------------------#
    # - echo $REGISTRY_ADDRESS/$PROJECT_IMAGE_PREFIX-$CI_PROJECT_NAME:$BASE_REF_NAME
    # - PORTAINER_HOST=$PORTAINER_HOST portainer login -u $PORTAINER_USERNAME -p $PORTAINER_PASSWORD
    # - touch $FILE_PATH/$PORTAINER_YML_FILE
    # - rm -rf  $FILE_PATH/$PORTAINER_YML_FILE && PORTAINER_HOST=$PORTAINER_HOST portainer stackfile $STACK_ID $FILE_PATH/$PORTAINER_YML_FILE
    # - sed -i "s/${CI_PROJECT_NAME}:.*/${CI_PROJECT_NAME}:${CI_COMMIT_REF_NAME}-${CI_PIPELINE_ID}/g" $FILE_PATH/$PORTAINER_YML_FILE
    # - echo 'updating data-store'
    # - PORTAINER_HOST=$PORTAINER_HOST portainer stack:update  $ENDPOINT_ID  $STACK_ID  $FILE_PATH/$PORTAINER_YML_FILE
  only:
    - 'nullnet-development'

