version: '3.9'

networks:
  internal:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - '5432:5432' # Expose PostgreSQL on port 5432
    networks:
      - internal
    environment:
      POSTGRES_USER: admin # Replace with your desired username
      POSTGRES_PASSWORD: admin # Replace with your desired password
      POSTGRES_DB: webaccessibility # Replace with your desired database name
#     volumes:
#      - timescale-data:/var/lib/postgresql/data
    restart: always
  # datastore:
  #   image: datastore:pg 
  #   networks:
  #     - internal
  #   build:
  #     context: .
  #     dockerfile: dockerfile
  #   #command: 'npm run drizzle:generate'
  #   #command: 'npm run drizzle:migrate'
  #   ports:
  #     - 5001:5001
  #     - 6000:6000
  #   environment:
  #     PORT: 5001
  #     GRPC_PORT: 6000
  #     SYNC_ENABLED: false
  #     BATCH_SYNC_ENABLED: false
  #     SYNC_ENDPOINT: http://localhost:5000
  #     BATCH_SYNC_SIZE: 100
  #     BATCH_SYNC_TYPE: weighted-round-robin #round-robin, weighted-round-robin
  #     GROUP_ID: 01JBHKXHYSKPP247HZZWHA3JBT
  #     SYNC_TIMER_MS: 5000
  #     DATABASE_URL: postgres://admin:admin@timescaledb:5432/webaccessibility
  #     DB_HOST: 0.0.0.0
  #     DB_NAME: webaccessibility
  #     DB_USER: admin
  #     DB_PASSWORD: admin
  #     DB_PORT: 5432
  #     DATABASE: webaccessibility
  #     DB_FILE_DIR: 'sql'
  #     DB_FILE_SQLITE: 'sqlite.db'
  #     NODE_ENV: 'local'
  #     DEBUG: 'false'
  #     STORAGE_UPLOAD_PATH: './upload'
  #     STORAGE_ENDPOINT: '10.6.100.1'
  #     STORAGE_PORT: 9000
  #     STORAGE_ACCESS_KEY: '0eYyLxBNBFdQlXly6E8F'
  #     STORAGE_SECRET_KEY: 'ZQ5PAdvYgj0iakLpocXTT4Eg5Rxs6muap2hwduL2'
  #     STORAGE_BUCKET_NAME: 'test'
  #     STORAGE_REGION: 'us-east-1'
  #     STORAGE_TIMEOUT: 10000
  #     SSL_CA: 'path/to/ca.cert'
  #     SSL_CERT: 'path/to/cert.cert'
  #     SSL_SECRET_KEY: 'path/to/secret.key'
  #     STORAGE_TRANSPORT_KEEPALIVE: false
  #     COMPANY_ORGANIZATION_ID: 'org-company-id-1'
  #     COMPANY_ORGANIZATION_NAME: 'org-company'
  # rtimescaledb:
  #   image: timescale/timescaledb:latest-pg14
  #   container_name: rtimescaledb
  #   ports:
  #     - '54324:5432' # Expose PostgreSQL on port 5432
  #   environment:
  #     POSTGRES_USER: admin # Replace with your desired username
  #     POSTGRES_PASSWORD: admin # Replace with your desired password
  #     POSTGRES_DB: nullnet_dev1 # Replace with your desired database name
  #   #  volumes:
  #   #    - rtimescale-data:/var/lib/rpostgresql/data
  #   restart: always

  # ttimescaledb:
  #   image: timescale/timescaledb:latest-pg14
  #   container_name: ttimescaledb
  #   ports:
  #     - '54325:5432' # Expose PostgreSQL on port 5432
  #   environment:
  #     POSTGRES_USER: admin # Replace with your desired username
  #     POSTGRES_PASSWORD: admin # Replace with your desired password
  #     POSTGRES_DB: nullnet_dev2 # Replace with your desired database name
  #   #  volumes:
  #   #    - ttimescaledb-data:/var/lib/rpostgresql/data
  #   restart: always
# volumes:
#  timescale-data:
#  rtimescale-data:
