# Use a newer Rust image that supports Cargo.lock v4
FROM rust:latest as builder

# Install build dependencies
RUN apt-get update && \
    apt-get install -y libpq-dev protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

# Set workspace
WORKDIR /usr/src/crdt-workspace

# Copy workspace
COPY . .

# Build server
RUN cargo install sccache --locked
ENV RUSTC_WRAPPER=sccache
WORKDIR /usr/src/crdt-workspace/bin/store
RUN cargo build --release

# Final image
FROM debian:bookworm

RUN apt-get update && \
    apt-get install -y libpq5 && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/src/crdt-workspace/target/release/store /usr/local/bin/store
COPY --from=builder /usr/src/crdt-workspace /usr/src/crdt-workspace

# Set the startup command
CMD ["store"]
