CREATE INDEX `config_applications_id_idx` ON `config_applications` (`id`);--> statement-breakpoint
CREATE INDEX `config_applications_tombstone_idx` ON `config_applications` (`tombstone`);--> statement-breakpoint
CREATE INDEX `config_applications_status_idx` ON `config_applications` (`status`);--> statement-breakpoint
CREATE INDEX `config_applications_version_idx` ON `config_applications` (`version`);--> statement-breakpoint
CREATE INDEX `config_applications_created_date_idx` ON `config_applications` (`created_date`);--> statement-breakpoint
CREATE INDEX `config_applications_created_time_idx` ON `config_applications` (`created_time`);--> statement-breakpoint
CREATE INDEX `config_applications_updated_date_idx` ON `config_applications` (`updated_date`);--> statement-breakpoint
CREATE INDEX `config_applications_updated_time_idx` ON `config_applications` (`updated_time`);--> statement-breakpoint
CREATE INDEX `contact_emails_id_idx` ON `contact_emails` (`id`);--> statement-breakpoint
CREATE INDEX `contact_emails_tombstone_idx` ON `contact_emails` (`tombstone`);--> statement-breakpoint
CREATE INDEX `contact_emails_status_idx` ON `contact_emails` (`status`);--> statement-breakpoint
CREATE INDEX `contact_emails_version_idx` ON `contact_emails` (`version`);--> statement-breakpoint
CREATE INDEX `contact_emails_created_date_idx` ON `contact_emails` (`created_date`);--> statement-breakpoint
CREATE INDEX `contact_emails_created_time_idx` ON `contact_emails` (`created_time`);--> statement-breakpoint
CREATE INDEX `contact_emails_updated_date_idx` ON `contact_emails` (`updated_date`);--> statement-breakpoint
CREATE INDEX `contact_emails_updated_time_idx` ON `contact_emails` (`updated_time`);--> statement-breakpoint
CREATE INDEX `contact_phone_numbers_id_idx` ON `contact_phone_numbers` (`id`);--> statement-breakpoint
CREATE INDEX `contact_phone_numbers_tombstone_idx` ON `contact_phone_numbers` (`tombstone`);--> statement-breakpoint
CREATE INDEX `contact_phone_numbers_status_idx` ON `contact_phone_numbers` (`status`);--> statement-breakpoint
CREATE INDEX `contact_phone_numbers_version_idx` ON `contact_phone_numbers` (`version`);--> statement-breakpoint
CREATE INDEX `contact_phone_numbers_created_date_idx` ON `contact_phone_numbers` (`created_date`);--> statement-breakpoint
CREATE INDEX `contact_phone_numbers_created_time_idx` ON `contact_phone_numbers` (`created_time`);--> statement-breakpoint
CREATE INDEX `contact_phone_numbers_updated_date_idx` ON `contact_phone_numbers` (`updated_date`);--> statement-breakpoint
CREATE INDEX `contact_phone_numbers_updated_time_idx` ON `contact_phone_numbers` (`updated_time`);--> statement-breakpoint
CREATE INDEX `contacts_id_idx` ON `contacts` (`id`);--> statement-breakpoint
CREATE INDEX `contacts_tombstone_idx` ON `contacts` (`tombstone`);--> statement-breakpoint
CREATE INDEX `contacts_status_idx` ON `contacts` (`status`);--> statement-breakpoint
CREATE INDEX `contacts_version_idx` ON `contacts` (`version`);--> statement-breakpoint
CREATE INDEX `contacts_created_date_idx` ON `contacts` (`created_date`);--> statement-breakpoint
CREATE INDEX `contacts_created_time_idx` ON `contacts` (`created_time`);--> statement-breakpoint
CREATE INDEX `contacts_updated_date_idx` ON `contacts` (`updated_date`);--> statement-breakpoint
CREATE INDEX `contacts_updated_time_idx` ON `contacts` (`updated_time`);--> statement-breakpoint
CREATE INDEX `organization_domains_id_idx` ON `organization_domains` (`id`);--> statement-breakpoint
CREATE INDEX `organization_domains_tombstone_idx` ON `organization_domains` (`tombstone`);--> statement-breakpoint
CREATE INDEX `organization_domains_status_idx` ON `organization_domains` (`status`);--> statement-breakpoint
CREATE INDEX `organization_domains_version_idx` ON `organization_domains` (`version`);--> statement-breakpoint
CREATE INDEX `organization_domains_created_date_idx` ON `organization_domains` (`created_date`);--> statement-breakpoint
CREATE INDEX `organization_domains_created_time_idx` ON `organization_domains` (`created_time`);--> statement-breakpoint
CREATE INDEX `organization_domains_updated_date_idx` ON `organization_domains` (`updated_date`);--> statement-breakpoint
CREATE INDEX `organization_domains_updated_time_idx` ON `organization_domains` (`updated_time`);--> statement-breakpoint
CREATE INDEX `organization_contact_accounts_id_idx` ON `organization_contact_accounts` (`id`);--> statement-breakpoint
CREATE INDEX `organization_contact_accounts_tombstone_idx` ON `organization_contact_accounts` (`tombstone`);--> statement-breakpoint
CREATE INDEX `organization_contact_accounts_status_idx` ON `organization_contact_accounts` (`status`);--> statement-breakpoint
CREATE INDEX `organization_contact_accounts_version_idx` ON `organization_contact_accounts` (`version`);--> statement-breakpoint
CREATE INDEX `organization_contact_accounts_created_date_idx` ON `organization_contact_accounts` (`created_date`);--> statement-breakpoint
CREATE INDEX `organization_contact_accounts_created_time_idx` ON `organization_contact_accounts` (`created_time`);--> statement-breakpoint
CREATE INDEX `organization_contact_accounts_updated_date_idx` ON `organization_contact_accounts` (`updated_date`);--> statement-breakpoint
CREATE INDEX `organization_contact_accounts_updated_time_idx` ON `organization_contact_accounts` (`updated_time`);--> statement-breakpoint
CREATE INDEX `organization_contacts_id_idx` ON `organization_contacts` (`id`);--> statement-breakpoint
CREATE INDEX `organization_contacts_tombstone_idx` ON `organization_contacts` (`tombstone`);--> statement-breakpoint
CREATE INDEX `organization_contacts_status_idx` ON `organization_contacts` (`status`);--> statement-breakpoint
CREATE INDEX `organization_contacts_version_idx` ON `organization_contacts` (`version`);--> statement-breakpoint
CREATE INDEX `organization_contacts_created_date_idx` ON `organization_contacts` (`created_date`);--> statement-breakpoint
CREATE INDEX `organization_contacts_created_time_idx` ON `organization_contacts` (`created_time`);--> statement-breakpoint
CREATE INDEX `organization_contacts_updated_date_idx` ON `organization_contacts` (`updated_date`);--> statement-breakpoint
CREATE INDEX `organization_contacts_updated_time_idx` ON `organization_contacts` (`updated_time`);--> statement-breakpoint
CREATE INDEX `organization_files_id_idx` ON `organization_files` (`id`);--> statement-breakpoint
CREATE INDEX `organization_files_tombstone_idx` ON `organization_files` (`tombstone`);--> statement-breakpoint
CREATE INDEX `organization_files_status_idx` ON `organization_files` (`status`);--> statement-breakpoint
CREATE INDEX `organization_files_version_idx` ON `organization_files` (`version`);--> statement-breakpoint
CREATE INDEX `organization_files_created_date_idx` ON `organization_files` (`created_date`);--> statement-breakpoint
CREATE INDEX `organization_files_created_time_idx` ON `organization_files` (`created_time`);--> statement-breakpoint
CREATE INDEX `organization_files_updated_date_idx` ON `organization_files` (`updated_date`);--> statement-breakpoint
CREATE INDEX `organization_files_updated_time_idx` ON `organization_files` (`updated_time`);--> statement-breakpoint
CREATE INDEX `organizations_id_idx` ON `organizations` (`id`);--> statement-breakpoint
CREATE INDEX `organizations_tombstone_idx` ON `organizations` (`tombstone`);--> statement-breakpoint
CREATE INDEX `organizations_status_idx` ON `organizations` (`status`);--> statement-breakpoint
CREATE INDEX `organizations_version_idx` ON `organizations` (`version`);--> statement-breakpoint
CREATE INDEX `organizations_created_date_idx` ON `organizations` (`created_date`);--> statement-breakpoint
CREATE INDEX `organizations_created_time_idx` ON `organizations` (`created_time`);--> statement-breakpoint
CREATE INDEX `organizations_updated_date_idx` ON `organizations` (`updated_date`);--> statement-breakpoint
CREATE INDEX `organizations_updated_time_idx` ON `organizations` (`updated_time`);