[registries.dnamicro]
index = "sparse+https://crates.dnamicro.net/api/v1/crates/"
credential-provider = ["cargo:token"]
token = "Lwqk5bDbiGF6uDfusdGFmKlrngugMIKs"

[build]
# rustc-wrapper = "sccache"
