networks:
  internal:
  frontend:
    external: true

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    ports:
      - "5432:5432"
    networks:
      - internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: store
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379" # Host:Container mapping
    networks:
      - internal
    restart: unless-stopped