networks:
  internal:
  frontend:
    external: true

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    ports:
      - "5432:5432"
    networks:
      - internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: store
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379" # Host:Container mapping
    networks:
      - internal
    restart: unless-stopped

  portal:
    build:
      context: /Users/chaosumaru/Documents/Projects/Platforms/v7/platform/DB/API/rust-projects/portal/tenant-portal
      dockerfile: Dockerfile
    container_name: tenant-portal
    ports:
      - "3000:3000"
    environment:
      # Rust/Application Config
      - RUST_LOG=info
      - DATABASE_URL=postgresql://postgres:admin@timescaledb:5432/store
      - REDIS_URL=redis://redis:6379
      
      # Application Environment
      - DEBUG=true
      - NODE_ENV=local
      - OPERATION_TIMEOUT=1000
      
      # Store Service
      - STORE_URL=http://store:5000
      
      # Google Places API
      - GOOGLE_PLACES_API_KEY=AIzaSyCNDmLeX_vZYnZolZSRMRZJSSuKLG3s2C8
      - PLACES_API=https://api.places.platform.dnadev.net
      
      # Email Configuration
      - MAILER_AUTH_USER=admin@dnaplatform.net
      - MAILER_AUTH_PASS=w@ckyPart10
      - MAILER_HOST=smtp.communications.dnamicro.net
      - MAILER_PORT=25
      
      # Root Account
      - ROOT_ACCOUNT_PASSWORD=pl3@s3ch@ng3m3!!
      
      # Schedule API Configuration
      - SCHEDULE_API=http://api.events.dnamicro.net/api/v1/schedule
      - SCHEDULE_AUTH_API=http://api.events.dnamicro.net/api/v1/auth
      - SCHEDULE_USERNAME=admin@dnamicro.com
      - SCHEDULE_PASSWORD=ch@ng3m3Pl3@s3!!
      
      # Socket Configuration
      - ROOM=portal-template
      - SOCKET_URL=http://pubsub.events.dnamicro.net
      - SOCKET_USERNAME=admin@dnamicro.com
      - SOCKET_PASSWORD=ch@ng3m3Pl3@s3!!
    depends_on:
      - timescaledb
      - redis
    networks:
      - internal
    volumes:
      - /Users/chaosumaru/Documents/Projects/Platforms/v7/platform/DB/API/rust-projects/portal/tenant-portal/logs:/app/logs
    restart: unless-stopped
    command: npm run local