{
 "title": "Datastore",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Server Errors",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_response_status_code)(rate(http_server_request_duration_count{http_response_status_code=~\"5..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_count[1m]))",
     "legendFormat": "server request per minute"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (http_response_status_code)(rate(http_server_request_duration_count{http_response_status_code=~\"4..\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}